### ISSUE TITLE
PLZ Eingabefeld leert sich bei Eingabe einer Nicht-Zahl

### ISSUE THREAD

**Issue by vlow** [qaware/wir-vs-virus#102]
Das PLZ Eingabefeld leert sich sobald ein Character eingegeben wird, der keine Zahl ist. Erwartung: Characters die keine Zahl sind werden einfach ignoriert.

**Comment by dominikhaas** [comment]
Tritt bei mir in Firefox auf, in Chrome nicht.

**Comment by dashuber** [comment]
done
