### ISSUE TITLE
Ortsdistanzen sind nicht nachvollziehbar

### ISSUE THREAD

**Issue by vlow** [qaware/wir-vs-virus#104]
Bei einem Laden in 81549 Giesing ist 85540 Haar näher als 81827 Trudering, das ist laut Maps nicht nachvollziehbar. Wie funktioniert die Distanzberechnung?

**Comment by adersberger** [comment]
Kann ich auch für meinen Wohnort so nachvollziehen: Holzkirchen ist nicht 15km und München nicht 45km weit weg - auch nicht Luftlinie.

**Comment by adersberger** [comment]
Die beiden Queries in `ShopDataRepository` scheinen nicht sauber zu funktionieren. Vorschlag: PostGIS verwenden und dort die eingebauten Distanzfunktionen verwenden.

**Comment by adersberger** [comment]
Ich habe die Klasse `DistanceUtil` hinzugefügt, die aus meiner Sicht die Distanz zwischen zwei Geo-Koordinaten richtig berechnet. Ich habe die Distanz-Berechnung in der Anwendung aber noch nicht damit ersetzt, da der Umbau von jemanden erfolgen sollte, der den Bestandscode besser kennt. Idee: Die Distanzberechnung weg aus dem `ShopDataRepository` nehmen und direkt in `ShopServiceImpl.findNearby()` aufrufen und die Ergebnisse damit anreichern.

**Comment by phxql** [comment]
Die Distanzberechnung hat @FelixKelm gebaut. Wir haben die direkt auf der Datenbank laufen lassen, ich paste hier mal den Code:

```
        "SELECT s as shopEntity, " +
            "sqrt(" +
            "  power(111.3 * cos((:latitude + s.latitude) / (2 * 0.01745)) * (:longitude - s.longitude) , 2)" +
            " + power(111.3 * (:latitude - s.latitude), 2)" +
            ") as distance FROM ShopEntity AS s " +
            "WHERE s.enabled = TRUE"
```

**Comment by phxql** [comment]
Woher diese sqrt Magie kommt, weiß ich nicht.

**Comment by vlow** [comment]
Da ist weder Sortierung, noch Pagination drin, oder? Gibt es einen guten Grund, die Berechnung trotzdem in der Datenbank zu machen? Aus dem Bauch heraus klingt das für mich nicht nach einer Kernkompetenz der DB und macht das ganze schlecht wart-  und testbar.

**Comment by vlow** [comment]
Vorschlag: Wir nutzen eine super einfache Logik, mit der wir die DB Requests filtern können, z.B. absolut Differenzen zwischen lat und long. Wenn es also mal zu viel Shops gibt, kann man filtern und grob sortieren. Die genaue Berechnung für die UI führen wir mit dem Dist Util durch. Meinungen?

**Comment by phxql** [comment]
Passt für mich, grobe Sortierung/Filterung per SQL, genaues zeug per Java code.

**Comment by phxql** [comment]
Hab den Code geändert und auf `test` deployed, schau mal ob es nun besser ist :)

**Comment by vlow** [comment]
Mit dem merge von #169 behoben.
