### ISSUE TITLE
Terminbuchung funktioniert nicht mehr

### ISSUE THREAD

**Issue by vlow** [qaware/wir-vs-virus#112]
Beim Buchen eines Termins fliegt ein 400er vom Backend:

```
Error booking time slot: 400, Http failure response for http://localhost:4200/api/reservation/209c408c-c3a8-4ed0-baa8-bc34f1950428: 400 Bad Request
```

**Comment by phxql** [comment]
Wie sieht der Body aus?

**Comment by vlow** [comment]
```XHRPOSThttp://localhost:4200/api/reservation/209c408c-c3a8-4ed0-baa8-bc34f1950428
[HTTP/1.1 400 Bad Request 81ms]

	
JSON	
contact	"foo"
contactType	"FACETIME"
email	"foo@bar"
name	"bar"
slotId	"2020-03-26T09:40"
Request payload	

1

{"contact":"foo","contactType":"FACETIME","email":"foo@bar","name":"bar","slotId":"2020-03-26T09:40"}
```

**Comment by vlow** [comment]
Ist ein Validierungsfehler auf der slotId:
`Resolved [org.springframework.web.bind.MethodArgumentNotValidException: Validation failed for argument [1] in public void de.qaware.mercury.rest.reservation.ReservationController.createReservation(java.lang.String,de.qaware.mercury.rest.reservation.dto.request.CreateReservationDto) throws de.qaware.mercury.business.shop.ShopNotFoundException: [Field error in object 'createReservationDto' on field 'slotId': rejected value [2020-03-26T09:40]; codes [Pattern.createReservationDto.slotId,Pattern.slotId,Pattern.java.lang.String,Pattern]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [createReservationDto.slotId,slotId]; arguments []; default message [slotId],[Ljavax.validation.constraints.Pattern$Flag;@a5862ad,^[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{12}$]; default message [must match "^[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{12}$"]] ]`

**Comment by phxql** [comment]
Jo, ist ein bug. Fixe ich.

**Comment by phxql** [comment]
Ist aufm master, ich deploye neue.

**Comment by vlow** [comment]
Ja, da ist ne GUID Validation auf der SlotId, aber die ist eigentlich n timestamp.

**Comment by phxql** [comment]
Jo, doppeltes layer an validierung ftw :(

**Comment by vlow** [comment]
fixed
