### ISSUE TITLE
Shop ändern: befüllt die Kontaktdaten nicht vor

### ISSUE THREAD

**Issue by rohleder** [qaware/wir-vs-virus#118]
Bei "Roll`s Laden" werden beim Bearbeiten keine Kontaktdaten angezeigt:
![image](https://user-images.githubusercontent.com/11029373/77649543-51559080-6f6a-11ea-827f-867494eabcfd.png)

Obwohl sie laut Buchungsseite vorhanden sein müssten, siehe hier:
![image](https://user-images.githubusercontent.com/11029373/77649521-4a2e8280-6f6a-11ea-88db-42d7e4c479bc.png)

**Comment by rohleder** [comment]
Ich habe jetzt noch mal geschaut und egal was ich an meinem Shop ändere, die Daten werden nicht gespeichert. Es kommt aber auch keine Fehlermeldung. Da muss irgendetwas mit meinem Shop kaputt sein!?

**Comment by rohleder** [comment]
Also mit "Michael`s Laden" werden die Daten auch nicht vorbefüllt, ich kann den Shop aber ändern und speichern.

**Comment by phxql** [comment]
Hmm :( Das haben wir nicht implementiert, da es im Backend relativ viel Arbeit ist und wir dachten, wir brauchen das nicht. Jetzt müssen wir es wohl machen, siehe #29 .
