### ISSUE TITLE
Emails zur Erstellung/Deaktivierung/Aktivierung von Läden

### ISSUE THREAD

**Issue by vlow** [qaware/wir-vs-virus#121]
Bitte ergänzt noch Emails für folgende Fälle:

- [x] Ein Laden wurde von einem User erstellt

```
Hallo xxx,

danke für deine Registrierung auf lokaler.kaufen! Gleich geht es los - sobald wir deinen Laden freigeschaltet haben, informieren wir dich per Mail. Schau dir doch inzwischen folgende Seite an, damit du mit deinem Geschäft reibungslos auf lokaler.kaufen starten kannst: https://lokaler.kaufen/welcome

Viele Grüße

Dein lokaler.kaufen Team
```

- [x] Ein Laden wurde von einem Admin aktiviert

```
Hallo xxx,

es geht los, dein Laden ist jetzt freigeschaltet. Falls du noch Fragen hast, wirf am besten einen Blick auf https://lokaler.kaufen/support

Viele Grüße

Dein lokaler.kaufen Team
```

- [x] Ein Laden wurde von einem Admin deaktiviert

```
Hallo xxx,

ein Administrator hat deinen Laden auf lokaler.kaufen deaktiviert. Um Genaueres zu erfahren, wende dich bitte unter Angabe deines Ladens an support@lokaler.kaufen.

Viele Grüße

Dein lokaler.kaufen Team
```

**Comment by vlow** [comment]
Support Page bei Aktivierung, damit der User erst die FAQ und dann den Support bemüht. Support Mail bei Deaktivierung: Da gibts keinen Standardeintrag in der FAQ. Wenn man nicht weiß, warum man deaktiviert wurde, muss man nen Admin fragen.

**Comment by phxql** [comment]
Tasks:

- [ ] Habe `enableShopsOnCreation` in der Config zu `approveShopsOnCreation` umbenannt -> Nachziehen in der Test und Prod-Config.

**Comment by phxql** [comment]
Implementiert. Config-Change auf der Prod steht noch aus.
