### ISSUE TITLE
Kontaktdaten des Shop-Owners speichern

### ISSUE THREAD

**Issue by zalintyre** [qaware/wir-vs-virus#126]
Zu jedem Contact Type, den der Ladenbesitzer angibt, soll auch die dazugehörige Nummer / der Nickname in der Datenbank gespeichert werden.

**Comment by phxql** [comment]
Duplikat von #29. Halte ich nicht für MVP relevant.

@vlow ?

**Comment by vlow** [comment]
Das war ursprünglich der Plan, inzwischen ist allerdings #128 aufgetaucht, was dummerweise darauf zurückzuführen ist: Editiert man die Seite, sind die Nummern weg. Gibt man nicht alle Nummern nochmal ein: 400 beim Update. Da es eh auf der Roadmap war, ziehen wir es lieber vor und beheben den Bug damit ordentlich, anstatt jetzt nen Zwischenfix außenrum zu basteln. @zalintyre hat schon einiges dazu gemacht, wenn ich das richtig sehe.

**Comment by vlow** [comment]
Ein Duplikat ists trotzdem -> #29
