### ISSUE TITLE
UI Verbesserungen PLZ Suche

### ISSUE THREAD

**Issue by rohleder** [qaware/wir-vs-virus#127]
Hier der Versuch mit einer unbedarften Brille auf die Suche zu schauen:

![image](https://user-images.githubusercontent.com/11029373/77696492-c302fe00-6fad-11ea-8d1b-0edfc0cbe02e.png)

**Comment by dashuber** [comment]
@rohleder hättest du lieber ein zartes lila als Farbe für den Header in der Tabelle? 🙂 
Oder welche Farbe schwebt dir vor?

**Comment by dashuber** [comment]
Hast du eine Idee, wie wir die Distanz besser benennen könnten? "Entfernung zu dir", "Entfernt von dir"?

**Comment by vlow** [comment]
Vorschlag: Neue PLZ Suche und aktuelle PLZ anzeigen in einem: z.B. über der Tabelle ein "Läden in der Nähe von _81549_" und die PLZ ist ein Link auf die Frontseite für eine neue Suche. @rohleder was meinst du mit "Der Klick auf das logo alleine reicht nicht aus" - dass das nicht funktioniert, oder dass das von der UI her nicht reicht?

**Comment by vlow** [comment]
Die Suche bezieht sich auf die Shops, durchsucht aber auch die Details (Beschreibung). Vorschlag: das Watermark versehen: "Wonach suchst du heute?" So ist das z.B. beim Facebook Status gelöst.

**Comment by rohleder** [comment]
> Vorschlag: Neue PLZ Suche und aktuelle PLZ anzeigen in einem: z.B. über der Tabelle ein "Läden in der Nähe von _81549_" und die PLZ ist ein Link auf die Frontseite für eine neue Suche. @rohleder was meinst du mit "Der Klick auf das logo alleine reicht nicht aus" - dass das nicht funktioniert, oder dass das von der UI her nicht reicht?

Ich meinte nur, dass es noch einen expliziten Link brauche

**Comment by rohleder** [comment]
> Vorschlag: Neue PLZ Suche und aktuelle PLZ anzeigen in einem: z.B. über der Tabelle ein "Läden in der Nähe von _81549_" und die PLZ ist ein Link auf die Frontseite für eine neue Suche. @rohleder was meinst du mit "Der Klick auf das logo alleine reicht nicht aus" - dass das nicht funktioniert, oder dass das von der UI her nicht reicht?

Der Link funktioniert, ich meinte nur, dass es noch einen zusätzlichen Link braucht, so wie von dir vorgeschlagen.

**Comment by rohleder** [comment]
> @rohleder hättest du lieber ein zartes lila als Farbe für den Header in der Tabelle? 
> Oder welche Farbe schwebt dir vor?

Nur etwas weniger grau Ton fände ich gut.

**Comment by vlow** [comment]
> > @rohleder hättest du lieber ein zartes lila als Farbe für den Header in der Tabelle?
> > Oder welche Farbe schwebt dir vor?
> 
> Nur etwas weniger grau Ton fände ich gut.

Weniger grau as in "heller" oder "farbiger"?

**Comment by rohleder** [comment]
Shit, ich bin da nicht genau genug, sorry. Ich meinte helleres grau (dezenter), bei Farben wäre ich mir jetzt unsicher, das müsste man sich anschauen, macht jetzt aber keinen Sinn, da muss später eh noch mal ein Designer drüber.

**Comment by dashuber** [comment]
Wir haben die Shop Overview Page nochmal überarbeitet und versucht, verständlicher zu machen.
