### ISSUE TITLE
Keine Angabe von Kontaktmöglichkeiten beim Shop führt zu Fehler

### ISSUE THREAD

**Issue by rohleder** [qaware/wir-vs-virus#128]
Wenn man keine Kontaktmöglichkeiten beim Shop ändern angibt, erscheint ein Fehler:

![image](https://user-images.githubusercontent.com/11029373/77698161-710fa780-6fb0-11ea-8b1a-6e8a83e7a5d2.png)

**Comment by dashuber** [comment]
ist behoben und kann auf https://test.lokaler.kaufen ausprobiert werden

**Comment by rohleder** [comment]
![image](https://user-images.githubusercontent.com/11029373/77854101-6a6b7500-71e8-11ea-971e-07408c0c40a7.png)

**Comment by rohleder** [comment]
Habs gerade noch mal ausprobiert und einen Fehler erhalten, ich habe dann bei einem Kontaktfeld etwas eingetragen und dann ging`s

**Comment by dashuber** [comment]
Ah sorry, ich hatte dich falsch verstanden. Hab jetzt eine Validierung eingebaut, dass wir mindestens eine Kontaktmöglichkeit brauchen, sowohl bei Shop erstellen als auch Shop aktualisieren.
