### ISSUE TITLE
"Zurück zur Liste" Link auf der Buchungsseite

### ISSUE THREAD

**Issue by rohleder** [qaware/wir-vs-virus#130]
Auf der Buchungsseite bräuchte es noch einen "Zurück zur Liste" Link.

![image](https://user-images.githubusercontent.com/11029373/77698927-ba142b80-6fb1-11ea-890d-6d3572a865c8.png)

**Comment by dashuber** [comment]
done. Ich war außerdem noch so frei, die DetailsPage ein bisschen aufzuhübschen, dass wir diese 3 Cards los werden und dafür eine strukturierte haben.
