### ISSUE TITLE
Falscher E-Mail-Link auf Shop Detail Page

### ISSUE THREAD

**Issue by rohleder** [qaware/wir-vs-virus#131]
Ich habe in der Shop-Änderung keine Möglichkeit gesehen meine Emaildresse zu pflegen???
Dadurch wird auf meiner Shop Seite ein kaputter Link angezeigt:

![image](https://user-images.githubusercontent.com/11029373/77699814-61de2900-6fb3-11ea-856f-a92b7eef95ed.png)

**Comment by phxql** [comment]
Das ist Absicht, da wir ansonsten erneut die Email verifizieren müssten und das n Haufen Aufwand ist. Sehe ich nicht im MVP.

**Comment by rohleder** [comment]
Ok, mich hat`s nur gewundert, weil in den anderen Läden eine Email eingepflegt ist bzw. auf der Shop Detailseite eine Email angezeigt wird???
Siehe hier:
![image](https://user-images.githubusercontent.com/11029373/77737346-11e08000-700e-11ea-909e-68029591b3fd.png)

**Comment by rohleder** [comment]
Wenn wir es nicht pflegbar machen, dann bitte rausnhemen von der Detailseite sonst kommen da unnötige Fragen, der Link "Roll`s Laden" geht ins Leere:

![image](https://user-images.githubusercontent.com/11029373/77737424-376d8980-700e-11ea-8d61-a652dbb07400.png)

**Comment by phxql** [comment]
Das mit dem Link sieht nach einem Bug aus. @dashuber ?

**Comment by dashuber** [comment]
Ich vermute, du hast deinen Laden angelegt, als noch keine Validierung auf der E-Mail stattgefunden hat? Weder im Backend, noch im Frontend, weil ich das auch von euch aus dem Backend als "valide" Mailadresse bekomme. Deswegen sehe ich das eigentlich nicht als Bug an. 
Oder versteh ich das Problem grad nicht richtig? 
Was wir machen können: Den Shop dann über die Admin UI löschen und du legst einen neuen an @rohleder?

**Comment by rohleder** [comment]
Das habe ich bereits gemacht: bei der Neuanlage kann ich keine Emailadresse pflegen, was dazu führt, dass auf der Shop-Detailseite ein kaputter Link erscheint.
Wie die anderen Shops zu Ihren Emailadressen gekommen sind, weiß ich nicht. Ggfs. gab es die Eingabemöglichkeit zu einem früheren Zeitpunkt mal und ist dann wieder entfernt worden?

**Comment by dashuber** [comment]
Wenn du dich neu als Ladenbesitzer registrierst mit einer richtigen E-Mail Adresse geht das nicht?

**Comment by rohleder** [comment]
"Michael`s Laden" habe ich gestern Abend angelegt, da hat es nicht geklappt:

![image](https://user-images.githubusercontent.com/11029373/77746099-b5389180-701c-11ea-8228-ba178dbe4296.png)

**Comment by rohleder** [comment]
Der Link zeigt auf mailto:Michael`s%20Laden

**Comment by vlow** [comment]
Das ist komisch, @rohleder mit welcher E-Mail Adresse hast du dich den registriert? Ich konnte das gerade auf keiner Umgebung reproduzieren...

**Comment by rohleder** [comment]
rohleder10@googlemail.com

Ladenbesitzer Login geht auch noch mit der Mail.

**Comment by rohleder** [comment]
soll ich dir das PWD separat schicken?

**Comment by vlow** [comment]
Oh, warte mal... Das ist n Backtick... @phxql haben wir hier ne SQL Injection?

**Comment by vlow** [comment]
Es steht noch der richtige Wert in der DB, sonst könnte sich Michael nicht anmelden, aber wir bekommen definitiv den Laden des Namens im E-Mail Feld zurück, wenn wir einen Backtick im Namen haben, das kann ich reproduzieren: https://test.lokaler.kaufen/#/shops/069e4fb6-9e5b-49d7-98e5-0a5de0a97416

**Comment by phxql** [comment]
lol, wtf. Ich schau's mir an.

**Comment by phxql** [comment]
Fix auf test deployed. Kann nachgetestet werden. Ich fix auch die Email-Adresse wieder.

**Comment by phxql** [comment]
Bug war falscher Code in der shop-update methode, nix SQL injection oder so :)
