### ISSUE TITLE
Aussagekräftigere Fehlermeldung, wenn die Registrierung fehlschlägt

### ISSUE THREAD

**Issue by FelixKelm** [qaware/wir-vs-virus#136]
1. Anmeldeformular komplett ausgefüllt.
2. Abgeschickt und die Fehlermeldung erhalten "Tut uns leid! Dein Laden konnte nicht angelegt werden"

Erwartung: Ich bekomme einen Hinweis auf die problematische Eingabe oder eine Kontaktmöglichkeit.

Getestet auf demo.lokaler.kaufen am 28.3.2020 gegen 9:15Uhr mit "Pyramidenverleih Ramses".
Hab leider noch keinen Zugriff auf die Logs, daher nur diese wenigen Infos.

**Comment by dashuber** [comment]
nicht reproduzierbar, allerdings ist mir aufgefallen, dass im Backend, wenn die PLZ nicht gefunden wird, als default PLZ München eingegeben wird. Deshalb würde ich evtl. beim Shop registrieren einen Validator, der den Location Service anfragt einbauen. Allerdings haben wir dann bei sehr langsamen Verbindungen das Problem, dass das Feld solange nicht valide ist, wie wir keine Antwort vom Backend haben. Bitte um Meinungen @phxql @vlow @dominikhaas

**Comment by FelixKelm** [comment]
Konnte es reproduzieren. Die URL des Requests war: http://localhost:4200/api/shop?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwYXJhbWlkZW52ZXJsZWloLnJhbXNlc0B3ZWd3ZXJmZW1haWwuZGUiLCJuYmYiOjE1ODUzOTI0NjQsImlzcyI6Im1lcmN1cnktc2hvcC1jcmVhdGlvbiIsImlhdCI6MTU4NTM5MjQ2NH0.PddvtWnkJX4CpN

Ich mach das nochmal und ergänze ein komplettes curl.
