### ISSUE TITLE
Methode zum Admin Accounts anlegen

### ISSUE THREAD

**Issue by vlow** [qaware/wir-vs-virus#142]
Wir brauchen noch einen Weg, um Admin Accounts zu pflegen. MVP Vorschlag:

* Shell-Script, das eine E-Mail-Adresse, User Passwort, DB URL, DB, DB User und DB Passwort abfragt, das Passwort bcrypt hasht und sich dann mit der Datenbank verbindet, und dort ein INSERT Statement absetzt. Die E-Mail-Adresse hat ein unique constraint drauf und der INSERT failed, falls es die E-Mail schon gibt.

* Admin-Accounts löschen geht direkt in der DB.
* Admin-Account Passwörter ändern = löschen + neuanlegen

**Comment by phxql** [comment]
Wenn die Applikation mit `--add-admin` gestartet wird, kann man nun nen neuen Admin anlegen. Siehe https://github.com/qaware/wir-vs-virus/blob/master/backend/README.md#add-a-new-admin
