### ISSUE TITLE
Backend: Shop löschen funktioniert nicht 

### ISSUE THREAD

**Issue by dashuber** [qaware/wir-vs-virus#144]
Beim Löschen kommt ein übelster Fehler: 
`could not execute statement; SQL [n/a]; constraint [shop_login_shop_id_fkey]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement`

Folgender curl: 
`curl 'http://localhost:4200/api/admin/shop/8f78e812-270f-4eb2-a97c-975f95b0354b' -X DELETE -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:74.0) Gecko/20100101 Firefox/74.0' -H 'Accept: application/json, text/plain, */*' -H 'Accept-Language: de,en-US;q=0.7,en;q=0.3' --compressed -H 'Origin: http://localhost:4200' -H 'Connection: keep-alive' -H 'Referer: http://localhost:4200/' -H 'Cookie: mercury-admin=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhY2VlZmExZS0yZDdkLTQyZmItOThhOC1mZDNjOTQyYmIwNTgiLCJuYmYiOjE1ODU0MDMxMDYsImlzcyI6Im1lcmN1cnktYWRtaW4iLCJpYXQiOjE1ODU0MDMxMDZ9.s23bGVF_tREJz-PycjLa49XY0zQjCUqi81eexvm3vDU'`

@phxql @zalintyre

**Comment by phxql** [comment]
Done, habe cascading deletes auf die FKs gesetzt. Nun tut alles wie es soll.
