### ISSUE TITLE
Frontend: Öffnungszeiten in Shop-Details anzeigen

### ISSUE THREAD

**Issue by callmemarv** [qaware/wir-vs-virus#145]
Als Kunde würde ich gerne die Öffnungszeiten in den Shop-Details sehen, insb. wenn gerade keine Termine zur Verfügung stehen.

@dashuber

**Comment by dashuber** [comment]
related to #41 
Wir könnten allerdings einen Endpunkt anbieten, der die SlotsConfigDto für einen Shop zurückliefert, um die generellen Öffungszeiten anzubieten. @phxql @vlow

**Comment by phxql** [comment]
Die frage hier ist, ob die Zeiten, zu denen Anrufe entgegen genommen werden, auch die gleichen sind, zu denen der Laden offen hat. Öffnungszeiten sollten auch in Google Maps etc. stehen.

**Comment by callmemarv** [comment]
Ich sehe den Mehrwert darin, zu wissen, wann ich wieder einen Anruftermin vereinbaren kann.

**Comment by phxql** [comment]
Wir haben nun die nächsten 7 Tage in der UI, um Slots zu reservieren. Damit hat sich das hier erledigt, oder?

**Comment by callmemarv** [comment]
👍

**Comment by vlow** [comment]
Wir sollten Tage, an denen keine Slots angeboten werden in der Tabansicht noch grau darstellen (und ggf. deaktivieren). Damit sehen Kunden die Tage ohne "Öffnungszeiten" auf den ersten Blick.

**Comment by dashuber** [comment]
done
