### ISSUE TITLE
Frontend: Kontaktmöglichkeiten in Shop-Details anzeigen

### ISSUE THREAD

**Issue by callmemarv** [qaware/wir-vs-virus#146]
Als Kunde würde ich gerne die Kontaktmöglichkeiten in den Shop-Details sehen, unabhängig davon ob ich gerade einen Termin vereinbaren möchte oder kann.

@dashuber

**Comment by dashuber** [comment]
Grundsätzlich ist die Idee nach einem Rückruf-Prinzip, der Kunde sieht die Telefonnummer o. Ä. des Ladenbesitzers gar nicht, sondern nur beim Termin ausmachen die Kontaktmöglichkeit. 
Ich glaube, das war fachlich auch so gedacht oder @vlow? 
1. Wollen wir die Kontaktmöglichkeiten (WhatsApp, Signal, ...) anzeigen? Das kriegen wir soweit ich weiß jetzt auch schon, also könnten wir die Icons der Kontaktmöglichkeiten bei den Details des Shops anzeigen. 
2. Wollen wir die wirklichen Telefonnummern etc. anzeigen?

**Comment by callmemarv** [comment]
@dashuber Ja, ich meinte die gleiche Anzeige, die ich auch in der Liste sehen kann.

**Comment by dashuber** [comment]
Coole Idee, bau ich ein! Und eindeutig ein Bug, dass in der Übersichtsseite die Kontaktmöglichkeiten angezeigt werden und in den Details nicht 🤦‍♀

**Comment by dashuber** [comment]
done, selbe Komponente wie bei der Overview Page verwendet und diese in dem Zuge auch gleich raus refactored
