### ISSUE TITLE
Frontend: Hovern über Items in Shop-Liste macht Curser nicht zum Pointer

### ISSUE THREAD

**Issue by callmemarv** [qaware/wir-vs-virus#147]
Beim Hovern über die Shop-Liste war mir nicht klar, dass ich die ganze Karte anklicken kann um auf die Shop-Details zu kommen, weil der Curser kein Pointer wird.

Mac OS X 10.15
Firefox 74.0

@dashuber

**Comment by dashuber** [comment]
Ist schon gefixt, nur noch nicht auf der Demo Seite 🙂
