### ISSUE TITLE
Frontend: Speichern von Shop-Details ist unter Reiter "Geschafft"

### ISSUE THREAD

**Issue by callmemarv** [qaware/wir-vs-virus#149]
Der Button zum Speichern der Shop-Details ist unter dem Reiter "Geschafft" zu finden. Für das Anlegen eines neuen Shops finde ich das sehr intuitiv, beim Speichern von Änderungen fand ich das eher verwirrend.

@dashuber

**Comment by dashuber** [comment]
Würdest du denn Reiter ganz weglassen oder nur umbenennen?

**Comment by callmemarv** [comment]
Im Dialog zum Aktualisieren würde ich ihn weglassen.

**Comment by dashuber** [comment]
Hmm, ich find's halt ganz charmant, dass wenn ich meine Beschreibung ändere, dann auf den 'Geschafft' Reiter klicken kann und intuitiv weiß, dass ich dort dann updaten kann. Ich würde ihn also eher in 'Fertig!' umbenennen?

**Comment by callmemarv** [comment]
Ja es ist nicht die unintuitivste Sache der Welt. ^^ "Geschafft" passt in meinen Augen besser zu den fünf anderen Reitern, das würde ich dann schon so lassen.

Wo würdest du einen Button "Abbrechen" hinsetzen?

**Comment by dashuber** [comment]
Beim Update sind die Reiter nicht mehr linear, heißt du kannst welche überspringen, deswegen hatte ich an 'Fertig!' gedacht. Gute Frage, bisher noch nicht angedacht gewesen. Wir könnten einen 'Zurück zur Übersicht' Button wie beim Anschauen der Shop Details machen?

**Comment by dashuber** [comment]
Hab den 'Geschafft' Reiter jetzt komplett rausgenommen und unten einen 'Änderungen speichern' Button eingefügt. Über Abbrechen sollten wir uns trotzdem gesondert Gedanken machen. (Evtl. redirect auf die Details Page des Shops?)
