### ISSUE TITLE
Elastic APM aufsetzen

### ISSUE THREAD

**Issue by phxql** [qaware/wir-vs-virus#152]

**Comment by phxql** [comment]
Haben nun ein APM. Logs sind noch nicht drin, das ist etwas mehr Arbeit.

**Comment by phxql** [comment]
Die TraceId, die wir rausgeben, wird bisher unabhängig vom APM generiert. Wir könnten uns überlegen, wenn die Anwendung mit APM läuft, dessen TraceId zu verwenden. API hier: https://www.elastic.co/guide/en/apm/agent/java/1.x/public-api.html

**Comment by vlow** [comment]
das ist erledigt, oder?

**Comment by phxql** [comment]
Jo, APM ist da.
