### ISSUE TITLE
Tabstop bei Passwort-Aufdecken Button verschieben

### ISSUE THREAD

**Issue by vlow** [qaware/wir-vs-virus#154]
Erwartung: Beim Eingeben von Passwörtern wechselt der Cursor per Tab vom Passworteingabefeld in das Passwortwiederholfeld. Der erste Tab landet aber auf dem Passwort-Aufdecken Button.

Bitte so anpassen, dass der erste Tabstop in das Passwortwiederholfeld wechselt. Der Aufdeckbutton ist eigentlich Teil des Eingabefeldes und benötigt IMHO keinen eigenen Tabstop.

**Comment by dashuber** [comment]
done
