### ISSUE TITLE
Abschicken einer Buchung mit Enter

### ISSUE THREAD

**Issue by zalintyre** [qaware/wir-vs-virus#155]
Die Enter-Taste macht im Moment nichts.

**Comment by zalintyre** [comment]
Nicht alle Form-Fields waren wirklich im `<form>`. Jetzt kann man mit der Enter-Taste das Formular abschicken.

Weil aber bei der Form Validation nur der submit-Button ausgegraut wird, kann ich das ungültige Formular trotzdem mit Enter abschicken. @defaude @dominikhaas pls assist (:

**Comment by dashuber** [comment]
done
