### ISSUE TITLE
Vorbelegung der Öffnungszeiten variiert

### ISSUE THREAD

**Issue by vlow** [qaware/wir-vs-virus#159]
Aus irgendeinem Grund bekommt man beim Anlegen neuer Shops manchmal in der Vorauswahl Samstag und Sonntag mit ausgewählt und manchmal nicht. Nicht wirklich schlimm, aber super seltsam. Zielbild: Samstag und Sonntag sind nicht vorausgewählt.

**Comment by dashuber** [comment]
leider schwer zu reproduzieren, hast du irgendeinen Anhaltspunkt, wann das passier? Im Code sieht alles gut aus 🤷‍♀

**Comment by dashuber** [comment]
nicht mehr aufgetreten
