### ISSUE TITLE
Shop Liste wird im Internet Explorer nicht angezeigt

### ISSUE THREAD

**Issue by rohleder** [qaware/wir-vs-virus#161]
![image](https://user-images.githubusercontent.com/11029373/77853688-c7b1f700-71e5-11ea-9c81-296079d1dd50.png)

Im Chrome, Firefox funktioniert`s

**Comment by dashuber** [comment]
@defaude ich vermute, das liegt an dem responsive Zeug / breakpoint observer?

**Comment by zalintyre** [comment]
Mit zwei eingebundenen Polyfills wird die Shopliste auch im IE angezeigt.
Das hash based routing ist dann aber kaputt.

**Comment by vlow** [comment]
@zalintyre Hat sich das mit dem Hash Based Routing jetzt geklärt?

**Comment by defaude** [comment]
Bitte mehr Input hierzu:
- Welche Version von IE genau? 10? 11?
- Welche Polyfills hast Du versucht einzubauen?
- Was genau ist am hash based routing kaputt?
- Mal in die Entwicklerkonsole im IE geschielt, welche Fehlermeldungen auftauchen?

**Comment by defaude** [comment]
Weitere Frage an Alle: Wir gehen ja wohl bald vor Kunde und Kunden-Kunde live. Wir sollten immer mal in die Logs gucken und auflisten, ob der IE überhaupt relevant ist. Ggf. können wir uns viel Aufwand sparen, wenn wir die IE-bezogenen Tickets einfach skippen. ;)

**Comment by dashuber** [comment]
3% der User

**Comment by vlow** [comment]
Die Seite funktioniert im Internet Explorer, auch wenn das Layout nicht so aussieht, wie es soll. Wir verfolgen das Fixen des Layouts in einem anderen Ticket (#183), da dieses hier inhaltlich erschöpft ist.
