### ISSUE TITLE
Zurück zur PLZ Suche als expliziten Link

### ISSUE THREAD

**Issue by rohleder** [qaware/wir-vs-virus#162]
Aktuell kommt man nur auf die PLZ Suche zurück, wenn man auf das Logo klickt. Das wird nicht jeder User intuitiv verstehen, daher Empfehlung: noch einen expliziten Link mit Beschreibung ergänzen: "neue Suche nach Postleitzahl" oder so ähnlich

**Comment by dashuber** [comment]
![grafik](https://user-images.githubusercontent.com/35682823/77857427-a6f59b80-71fd-11ea-932d-947cba914bbe.png)
Wir haben das jetzt darüber gelöst, dass wir ein PLZ Input Field bei der Übersichtsseite haben, das editierbar ist. Was hältst du davon @rohleder?

**Comment by rohleder** [comment]
Wunderbare Idee

**Comment by dashuber** [comment]
Super 🙂
