### ISSUE TITLE
Bei der Änderung eines Shops sind die Beratungsdauer und Pausen wieder auf dem Default-Wert

### ISSUE THREAD

**Issue by rohleder** [qaware/wir-vs-virus#164]
Wenn ich die Beratungsdauer und Pausen ändere und danach wieder meinen Shop bearbeite stehen bei den beiden Feldern wieder die Defaultwerte drin, habs mit verschiedenen Kombinationen getestet:
![image](https://user-images.githubusercontent.com/11029373/77854623-99371a80-71eb-11ea-998a-cd79854994b8.png)

**Comment by zalintyre** [comment]
Werte werden richtig aus dem Backend geliefert -> Frontend-Bug

**Comment by dashuber** [comment]
done, hatte ich schlichtweg vergessen
