### ISSUE TITLE
Verbesserung Darstellung Mobilversion

### ISSUE THREAD

**Issue by rohleder** [qaware/wir-vs-virus#167]
Auf der Mobilversion (Chrome, Pixel Handy) sind mir zwei Sachen aufgefallen:

1. Die Von Bis Angabe bei der Uhrzeit ist umgebrochen, obwohl eigentlich genügend Platz da wäre. Ist dann etwas unübersichtlich

![Screenshot_20200329-185421](https://user-images.githubusercontent.com/11029373/77855418-9a1e7b00-71f0-11ea-8188-8992d95ff06c.png)

2. Der Speichern Button ganz unten ist abgeschnitten:

![Screenshot_20200329-185413](https://user-images.githubusercontent.com/11029373/77855420-9b4fa800-71f0-11ea-84a4-19f6067e33f7.png)

**Comment by dashuber** [comment]
hab ein bisschen was versucht 😉
