### ISSUE TITLE
Mobilansicht wenn keine Suchergebnisse gefunden werden

### ISSUE THREAD

**Issue by vlow** [qaware/wir-vs-virus#170]
Wenn eine Suche erfolglos ist, collapsed die Website zur Mobilansicht.
![Screenshot from 2020-03-30 01-13-29](https://user-images.githubusercontent.com/3588976/77863598-df0fd500-7223-11ea-9a7b-5886047c5665.png)

**Comment by vlow** [comment]
Idealerweise zeigen wir einen Text an wie "Leider keine Ergebnisse zur Suche nach 'fifa' gefunden."

**Comment by dashuber** [comment]
done
