### ISSUE TITLE
Label bei 'Sonntag' fehlt

### ISSUE THREAD

**Issue by vlow** [qaware/wir-vs-virus#171]
Bei der Auswahl der Tage in der Shop Detail Page fehlt bei mir der Sonntag als Label, der Button geht aber...

![Screenshot from 2020-03-30 01-21-05](https://user-images.githubusercontent.com/3588976/77863758-d8ce2880-7224-11ea-9b79-025f9bc1f886.png)

**Comment by defaude** [comment]
![test lokaler kaufen_(iPhone 5_SE)](https://user-images.githubusercontent.com/57310/77877178-527e0a80-7255-11ea-9217-1dda2ad3f1da.png)

Auch auf mobile

**Comment by defaude** [comment]
![test lokaler kaufen_(iPhone 5_SE)](https://user-images.githubusercontent.com/57310/77877236-793c4100-7255-11ea-99c9-df9e72a27786.png)

Auch auf mobile

**Comment by dashuber** [comment]
lol, da wurde warum auch immer ein string concat gemacht statt einer Addition. Again what learned 😉
