### ISSUE TITLE
Infostring im Footer anzeigen

### ISSUE THREAD

**Issue by vlow** [qaware/wir-vs-virus#172]
Das Backend hat einen Info Endpunkt, über den diverse Informationen zu den Versionen (Backend Version, Commit Hash etc.) abgerufen werden können. Diese bitte zusammen mit der Frontend Version im Footer anzeigen. Z.B. als grauer Text.

**Comment by phxql** [comment]
```
╰─$ curlie :8080/api/info/version
HTTP/1.1 200 
X-Trace-Id: 287cf14abfa11975ccb4307257660cd7
Content-Type: application/json
Transfer-Encoding: chunked
Date: Tue, 31 Mar 2020 18:43:15 GMT

{
    "commitHash": "UNKNOWN",
    "commitTime": "1970-01-01T00:00Z",
    "localChanges": false,
    "version": "UNKNOWN"
}
```

**Comment by dashuber** [comment]
![grafik](https://user-images.githubusercontent.com/35682823/78066798-df2fe200-7395-11ea-84b5-bca9fd27a625.png)
Ist im Footer, selbe Farbe wie Hintergrund, wenn man es markiert, wird's sichtbar.
