### ISSUE TITLE
Einheitliche Ansprache der Nutzer

### ISSUE THREAD

**Issue by vlow** [qaware/wir-vs-virus#177]
Wir sollten Nutzer einheitlich Ansprechen. Nach ein bisschen Recherche sieht es so aus, als ob die meisten Portale "Siezen". Ich würde deshalb mal damit loslaufen. Derzeit vermute ich, dass die Abwehrhaltung von Personen, die das "Siezen" bevorzugen dagegen "geduzt" zu werden höher ist, als andersherum.

In diesem Zuge macht es Sinn darüber nachzudenken, zuerst #176 umzusetzen.

**Comment by callmemarv** [comment]
Ich könnte mich da direkt dran setzen, wenn das ok ist!?

**Comment by phxql** [comment]
Done im Backend.

**Comment by phxql** [comment]
Hab jetzt noch keine Properties rausgezogen - können wir für den Public Launch machen.

**Comment by zalintyre** [comment]
PR von @callmemarv gemerged und letzte Korrekturen gemacht.
