### ISSUE TITLE
Janitor Job aufsetzen

### ISSUE THREAD

**Issue by vlow** [qaware/wir-vs-virus#181]
Alle 24h alle nicht mehr benötigten Daten anonymisieren:

* E-Mail-Adressen von Kunden aus den Reservierungen
* Telefonnummern

**Comment by phxql** [comment]
Spalten der `reservation`-Tabelle anonymisieren:

- name
- contact
- email

Einmal um 3 Uhr in der Nacht mittels `@Scheduled` die vergangenen Reservierungen (mittels end_time) anonymsieren, z.b. durch `<anonymized>` ersetzen)
