### ISSUE TITLE
Login Token für Ladenbesitzer vorhalten

### ISSUE THREAD

**Issue by phxql** [qaware/wir-vs-virus#186]
1. Als Shop einloggen
1. Laden bearbeiten
1. Speichern -> bin nun auf der Shop-Detail-Seite vom User
1. Wie komm ich zurück zum Bearbeiten? Wenn ich unten auf "Login für Ladenbesitzer" klicke, muss ich mich nochmal einloggen (hab ich doch grade?)

**Comment by vlow** [comment]
Wir haben noch keinen Store im Frontend, deshalb verlieren wir den Zustand zwischen allen "Seitenwechseln". Mögliche Lösungen: Cookie setzen oder Store einbauen und nach dem Login Token speichern.

Beste Lösung: Beides. Haken bei "Ich möchte eingeloggt bleiben" setzt Cookie, ansonsten cachen wir das Token im Frontend für die Session.

**Comment by phxql** [comment]
Wir setzen so oder so ein Cookie. Meine vorgeschlagene Lösung:

Beim Navigieren auf `#/login` die Backend-API `GET /api/shop/login` aufrufen. Wenn 401, dann Login-Maske anzeigen, ansonsten direkt auf ShopDetails redirecten.
