### ISSUE TITLE
PLZ ist nicht eindeutig

### ISSUE THREAD

**Issue by phxql** [qaware/wir-vs-virus#189]
`84539` ist sowohl Ampfing als auch Zangberg (die sind ca 3 KM auseinander). Wenn man diese PLZ in die Landing-Page eingibt, taucht manchmal Ampfing und manchmal Zangberg in dem Drop-Down auf. Die haben in der Datenbank leicht unterschiedliche Koordinaten.

Wir könnten die Deduplizierung im Backend auf (PLZ, Name) machen statt nur auf PLZ oder direkt auf (Lat, Long).

**Comment by vlow** [comment]
Erstmal ist es ein Bug, dass man bei der Eingabe von 84539 nicht einfach beide angezeigt bekommen. Danach verwerfen wir den Ort aber auch komplett. Wir müssten ansonsten überall die Auswahl auf PLZ+Ort ändern. Beim Anlegen der Läden haben wir z.B. ein Freitextfeld für den Ort und machen das Location Matching nur auf Basis der PLZ, auch da müssen wir dann einen harten Match erzwingen. 

Auf den ersten Blick ist die Ungenauigkeit noch im Rahmen der Toleranz. Vorschlag zur Lösung: Bei exact Matches liefern wir im Auswahlfeld alle Orte zurück, egal wie viele das sind. Wir behalten die Berechnung erstmal bei, da sie im Rahmen der Ungenauigkeit auf PLZ Ebene derzeit trägt.

Wir sollten überlegen, ob wir den Ort bei der Shop Creation aber nur noch aus einem Dropdown auswählen lassen, statt dort ein Freitextfeld zu haben, sonst haben wir später super viel Aufwand bei der Datenbereinigung.

**Comment by vlow** [comment]
Backend-seitig gefixt, Frontend Anpassungen stehen noch aus.

**Comment by vlow** [comment]
Bitte im Frontend bei der Shop Creation und Shop Management Page die Stadt zu einer Combobox (Drop Down) machen und den User nur aus den Optionen auswählen lassen, die das Backend für die _vollständige_ eingegebene PLZ anbietet.

**Comment by phxql** [comment]
> Backend-seitig gefixt, Frontend Anpassungen stehen noch aus.

Da fehlt noch mehr: Jede API / DTO, die nur die PLZ beinhaltet, muss so umgebaut werden, dass sie nun auch den Namen annimmt - denn nur so können wir den Lookup auf die Lat/Long machen.

Ich würde vorschlagen, in die LocationSuggestion ne `id` reinzubauen. Die muss man bei allen Anfragen ans Backend, die vorher mit PLZ waren, mitgeben. Mit der können wir dann den Lookup auf Lat/Long machen.

`id` könnte z.b. `<zipCode>-<placename>` sein und wir splitten im Backend anhand `-`. Oder wir geben der `geolocation` tabelle ne echte id spalte und verwenden das als `id`.

**Comment by phxql** [comment]
Ich sehe das nicht im MVP - Seite funktioniert generell, haben halt ne kleinere Abweichung für n paar PLZs. Wir können notfalls die Lat/Long der Shops aus den Informationen in der `shop`-Tabelle berechnen (da steht der Ort auch drin). Die ganzen APIs zu ändern würd ich lieber in Ruhe machen und das gescheit testen.

**Comment by dashuber** [comment]
done
