### ISSUE TITLE
E-Mail Feld bei "Passwort vergessen" Popup zu klein

### ISSUE THREAD

**Issue by phxql** [qaware/wir-vs-virus#190]
1. Auf "Login für Ladenbesitzer" klicken
1. Auf "Passwort vergessen" klicken

**Comment by vlow** [comment]
Ist das ein reines Designproblem, weil das Textfeld nicht die ganze Breite ausfüllt? Ich bringe da Problemlos einiges an E-Mail-Adresse rein, bevor das Feld zu scrollen anfängt:

![Screenshot from 2020-03-31 16-06-31](https://user-images.githubusercontent.com/3588976/78035614-a11cc900-7369-11ea-8bed-b2c20ca046f4.png)

Einfach nur ein bisschen breiter machen oder auf die ganze Breite ziehen?

**Comment by phxql** [comment]
Reines Designproblem.

**Comment by dashuber** [comment]
Momentan sind alle Popups 500px breit, könnten das Input Field auf die ganze Breite strecken, find aber nicht, dass das besser ausschaut 😄
