### ISSUE TITLE
Invalide Zeitangabe wird beim Laden-Erstellen wird nich erkannt.

### ISSUE THREAD

**Issue by weberChristian** [qaware/wir-vs-virus#191]
Bei den Öffnungszeiten, kann man mit x die Zeit rausnehmen.

![grafik](https://user-images.githubusercontent.com/6974622/78009140-deb92c00-7340-11ea-85e1-17ff08f136fe.png)

Mit dieser Konfiguration, kann ich auf Weiter klicken. Beim Speichern erhalte ich dann die Fehlermeldung das ein Fehler aufgetreten ist - ohne weitere Erklärung. Nehme ich den Tag über den vorhergesehenen Mechanismus raus funktioniert das speichern...

Erwartungshaltung:
Wenn ein Tag unvollständig Konfiguriert ist, kann ich auch nicht auf Weiter klicken.

**Comment by dashuber** [comment]
done
