### ISSUE TITLE
Datenschutzerklärung beim Anlegen eines Shops abnicken

### ISSUE THREAD

**Issue by phxql** [qaware/wir-vs-virus#193]
Beim Anlegen eines Shops muss es eine Checkbox geben mit dem Label "Ich habe die [Datenschutzerklärung](https://test.lokaler.kaufen/#/privacy) gelesen und akzeptiere diese".

(Link natürlich auf die jeweilige Seite anpassen und im neuen Fenster aufgehen lassen)

Wenn diese Checkbox nicht angehakt ist, darf es nicht möglich sein, einen Laden zu registrieren.

Beim Ändern des Shops brauchen wir diese nicht nicht anzeigen.

**Comment by dashuber** [comment]
done
