### ISSUE TITLE
Beim Shop Bearbeiten wird der Ort nicht richtig vorausgewählt (falls mehrere zur Auswahl stehen)

### ISSUE THREAD

**Issue by rohleder** [qaware/wir-vs-virus#195]
Wenn ich in der Shop Bearbeitung beim Ort den zweiten angebotenen Ort auswähle und speichere, dann wird dieser übernommen. Beim Bearbeiten des Shops wird aber wieder der erste Ort vorausgewählt. In meinem Beispiel habe ich Staudach-Egerndach gespeichert und beim Bearbeiten wurde wieder Grassau ausgewählt:

![image](https://user-images.githubusercontent.com/11029373/78071431-c7f4f280-739d-11ea-8e8e-fd4dfa18d6c6.png)

**Comment by dashuber** [comment]
done
