### ISSUE TITLE
Datenschutzseite Rechtschreib QS

### ISSUE THREAD

**Issue by rohleder** [qaware/wir-vs-virus#196]
"inhaltlich":

![image](https://user-images.githubusercontent.com/11029373/78072817-0a1f3380-73a0-11ea-9273-74cbdb2962a3.png)

Hier "angegebenen" schreiben:

![image](https://user-images.githubusercontent.com/11029373/78072960-418de000-73a0-11ea-9589-249f55e7ed80.png)

**Comment by vlow** [comment]
done
