### ISSUE TITLE
Internet Explorer Banner

### ISSUE THREAD

**Issue by vlow** [qaware/wir-vs-virus#201]
Die zahlreichen Fixes für den Internet Explorer kosten uns viel Zeit. Vorerst könnten wir uns damit behelfen, dass wir für Benutzer mit IE/Edge anzeigen, dass wir den Internet Explorer nicht unterstützen und auf den Firefox verweisen.

**Comment by dashuber** [comment]
Ist auf test.lokaler.kaufen deployed und kann von fleißigen IE und Edge Explorer Nutzern getestet werden 😉 @rohleder

**Comment by phxql** [comment]
Funktioniert im IE 11.

**Comment by dashuber** [comment]
Kann's noch jemand im Edge testen?

**Comment by rohleder** [comment]
funktioniert im Edge

**Comment by dashuber** [comment]
super!
