### ISSUE TITLE
Frontend schickt `GET http://backend-prod/api/shop/nearby?zipCode=undefined` ans backend

### ISSUE THREAD

**Issue by phxql** [qaware/wir-vs-virus#205]
Siehe https://6a68d4ca63494dc787eb7f72d9e63a78.europe-west3.gcp.cloud.es.io:9243/app/apm#/services/mercury-prod/errors/c1bc130d592b15e0820e6b2eb81e8556?rangeFrom=now-24h&rangeTo=now&refreshPaused=true&refreshInterval=0&environment=

Safari (13.0.5) hat `GET http://backend-prod/api/shop/nearby?zipCode=undefined` ans backend geschickt. Wie das undefined da reingekommen ist, weiß ich nicht.

**Comment by dominikhaas** [comment]
Problem ist in der Detailseite. Da gibt es einen Link "Zurück zur Übersicht". Dieser lädt aus localStorage den letzten Wert von PLZ und schreibt ihn serialisert an die URL.
Wenn es noch keinen Wert gibt wird das zum Wert "undefined". Die Startseite öffnet und die PLZ Suche mit undefined wird getrigged.

**Comment by dominikhaas** [comment]
Ich passe das Ganze wie folgt an:
Wir rufen einfach ein Browser-Back auf. Damit müssen wir gar nichts auslesen und anhängen sondern springen einfach zurück.
Ich kenne zwei Fälle: 
- Übersicht -> Detail  //passt
- Shop-Editieren -> Detail //passt auch, wir kommen jetzt wieder auf die Editierseite, statt auf die Suche

Ich passe entsprechend zusätzlich das Label an von "Zurück zur Übersicht" auf "Zurück".

**Comment by dashuber** [comment]
@dominikhaas das issue kann ich schließen oder?
