### ISSUE TITLE
Logout link anbieten

### ISSUE THREAD

**Issue by dominikhaas** [qaware/wir-vs-virus#207]
Wir sollten meiner Meinung nach auch einen Login-Link anbieten (wenn der Ladenbesitzer eingeloggt ist). Der Link sollte das Cookie entfernen.

**Comment by phxql** [comment]
https://stackoverflow.com/questions/20320549/how-can-you-delete-a-cookie-in-an-http-response/20320610

**Comment by phxql** [comment]
```
curlie POST :8080/api/shop/login/logout
curlie POST :8080/api/admin/login/logout
```

**Comment by dashuber** [comment]
Hab den Link ins Frontend eingebaut, sollten uns dann nochmal absprechen, ob wir's in den Master mergen wollen.
