### ISSUE TITLE
Breite des Namens in der Shopliste anpassen

### ISSUE THREAD

**Issue by vlow** [qaware/wir-vs-virus#210]
Viele Shop-Namen sind länger als das Feld in der Liste zulässt und wir brechen um. Wir verschwenden ein bisschen Platz bei der Distanz. Wenn wir das Distanz Feld kleiner machen und den Platz dem Shop-Namens-Feld spendieren, haben wir weniger Umbrüche.

**Comment by dashuber** [comment]
Wenn wir das Feature einbauen, dass die Shops Bilder/Logos hochladen können, würde ich die Shopliste überarbeiten und keine Material Tabel mehr verwenden. Als quick bug fix, kann ich trotzdem die Distanz Spalte kleiner machen

**Comment by dashuber** [comment]
Namen brechen jetzt nicht mehr um, ich schließe das issue
