### ISSUE TITLE
E-Mail-Adressen beim Login nicht case-insensitive

### ISSUE THREAD

**Issue by phxql** [qaware/wir-vs-virus#213]
Bisher ist `Info@local.host` n anderes login als `info@local.host`, d.h. ich kann mich unter umständen mit der 1. version nicht im account anmelden.

Ich denke, aus Kundenerwartung ist das ein Bug, da vor allem manche Handy-Tastaturen das 1. Zeichen immer groß machen.

@vlow Deine Meinung dazu?

**Comment by vlow** [comment]
Jo, definitiv ein Bug aus Kundensicht. Bitte auf dem Bugfix Branch fixen.

**Comment by phxql** [comment]
Done, ist im `master` und auf `bugfix-1.0.2`
