### ISSUE TITLE
Einsprung für Ladenbesitzer prominenter machen

### ISSUE THREAD

**Issue by defaude** [qaware/wir-vs-virus#214]
> auch auf der App ist der Link "Als Ladenbesitzer registrieren" nicht ganz leicht zu finden

Stimmt. Geht besser. Ich mach mal was ;)

**Comment by defaude** [comment]
Was haltet Ihr von diesem Vorschlag?

![localhost_4200_(iPhone 5_SE) (1)](https://user-images.githubusercontent.com/57310/78338608-5f6f6680-7593-11ea-82be-37ce3fda2e6e.png)
![localhost_4200_(iPhone 5_SE)](https://user-images.githubusercontent.com/57310/78338613-61392a00-7593-11ea-8a64-f68e841c1384.png)
![screencapture-localhost-4200-2020-04-03-10_06_27](https://user-images.githubusercontent.com/57310/78338616-61d1c080-7593-11ea-917f-2ddcfbfa9081.png)
![screencapture-localhost-4200-2020-04-03-10_06_47](https://user-images.githubusercontent.com/57310/78338618-61d1c080-7593-11ea-8572-fbdceb59b69a.png)

**Comment by dashuber** [comment]
@vlow @phxql @rohleder Was haltet ihr davon?

**Comment by phxql** [comment]
Find ich gut

**Comment by defaude** [comment]
# Landing Page

## Normale Besucher

Hier werden prominent die nächsten Aktionen ausgestellt: Entweder PLZ Suche als Kunde oder Login als Ladenbesitzer oder Registrieren eines Ladens.

![landing-page_normal](https://user-images.githubusercontent.com/57310/78451887-688e2f80-7688-11ea-87b6-66d7c9c265f4.png)

## Eingeloggte Ladenbesitzer

Die "Registrieren" bzw. "Login" Aktionen verschwinden. Stattdessen werden in der ganzen App über der Hauptkarte ein direkter Link zu "Laden bearbeiten" sowie den Logout-Knopf angezeigt.

![landing-page-eingeloggt](https://user-images.githubusercontent.com/57310/78451949-d33f6b00-7688-11ea-937f-1c0312483c37.png)
![irgendwo-in-der-app_eingeloggt](https://user-images.githubusercontent.com/57310/78451970-eb16ef00-7688-11ea-9d57-9075caae7e2a.png)

**Comment by defaude** [comment]
Warum das Ganze:
- Login für Ladenbesitzer / Neuen Laden registrieren / Logout sollten prominent sein, da sie den Haupt-Klickpfad für die Ladenbesitzer ausmachen. Mit kleiner Schriftart in den Footer gequetscht (den sowieso Jeder halb-bewusst überliest) sind sie nicht sichtbar genug.
- Statische Links (Impressum usw.) mit Zustands-Aktionen vermischen fühlt sich auch irgendwie schräg an.
- Gut möglich, dass der Ladenbesitzer seine Daten editiert hat und dann über die Landing Page selbst "als Kunde" nach seinem Laden sucht - auch hier muss der Logout und der Rücksprung zum eigenen Laden (edit) immer und überall sichtbar sein.

PS: Auf den Admin-Seiten habe ich eine ähnliche Navigation eingebaut.

@rohleder @dashuber @vlow @phxql @zalintyre was haltet Ihr davon? Design ist sicher noch nicht optimal - ich hab versucht, eine Balance zwischen "prominent sichtbar" und "nicht zu aufdringlich" zu finden.

**Comment by vlow** [comment]
Ich versteh den Punkt und ich bin vollkommen dabei, dass wir da was tun müssen. Ich finde auch, dass das schon in die richtige Richtung geht. Ich stoße mich momentan eher noch an Details und bin mir deshalb auch nicht sicher, ob ich auf der richtigen Flughöhe unterwegs bin:

* Warum ist ein Laden bearbeiten Button sichtbar, wenn der User gerade den Laden bearbeitet?
* Momentan versuchen wir Ladenbesitzer und Kunden gleichermaßen anzusprechen, aber bei der dualen Loginpage stört mich insgesamt irgendwie, dass wir im Zielbild um einen großen Faktor mehr Kunden als Ladenbesitzer auf der Page haben wollen und wir einen großteil der Welcome Page für den Login der Ladenbesitzer spendieren, der für den Kunden irrelevant ist. Der Kunde muss jetzt auf "bin ich Kunde?" achten und wird damit zum Entscheidungsfall, während die Seite genau für Kunden sein soll, und der Ladenbesitzer der Sonderfall ist. Konsequenterweise wäre ich in meiner initialen Überlegung erstmal bei einem "Sind Sie Ladenbesitzer? Hier entlang..." gelandet, was auf den Login für Ladenbesitzer führt.
* Ladenbesitzer können dann ggf. ein eigenes Control wie einen eigenen Header etc. sehen, in dem sie die zusätzlichen Menüpunkte sehen, während User einfach nur unsere reguläre UI haben. Die Buttons (Login, Laden bearbeiten) verstoßen in meiner Sicht wieder gegen das von @defaude bereits richtig angesprochene Konzept der Separation of Concerns: Die UI ist für Kunden. Da Controls für Ladenbesitzer reinzuschmeißen ist unintuitiv und weicht das auf.

**Comment by vlow** [comment]
Implementiert als "Sind Sie Ladenbesitzer? Hier entlang..."-Link und Banner für eingeloggte Benutzer (Admin und Ladenbesitzer).
