### ISSUE TITLE
Bilder für Shop hochladen

### ISSUE THREAD

**Issue by phxql** [qaware/wir-vs-virus#216]
Shops sollen Bilder hochladen können. Ein Bild soll das "Icon" eines Shops werden, das auch in der Liste angezeigt wird. Beim Anlegen muss der Shop mindestens das Icon anlegen.

Wir müssen uns überlegen, welche Eingabeformate wir in welcher Dateigröße und Auflösung akzeptieren. Diese Bilder müssen dann skaliert und in ein Zielformat (Idee: JPEG 95%) gebracht werden. Diese Bilder werden dann irgendwo abgelegt und an das Frontend nur noch per URL referenziert.

Tasks:

- [x] Welche Eingabeformate? -> wir können alles, was ImageMagick lesen kann
- [x] Welche maximale Dateigröße? -> Max 5 MB
- [x] Welche maximale Auflösung? -> Keine Beschränkung im Moment
- [x] Welche Zielauflösung? -> Im Moment 500px, aber das ist konfigurierbar
- [x] Wie skalieren wir die Bilder? -> ImageMagick
- [x] Wie kodieren wir die Bilder in unser Zielformat? -> JPEG 90% quality (Qualität konfigurierbar)
- [x] Wo speichern wir die Bilder? -> Im lokalen Dateisystem
- [x] Wie generieren wir die URL auf diese gespeicherten Bilder fürs Frontend? -> Template in der Config
- [x] Wer liefert die Bilder aus? -> nginx, der als webroot den Ordner hat, in den mercury die Bilder ablegt (Option 2 von Kommentar unten)

TODOs:
- [ ] alle Shop DTOs anpassen, die beim Frontend ein Bild anzeigen sollen: `imageUrl` einbauen
- [ ] Shop-Login Cookie bei `POST /api/shop` (Shop erstellen) setzen
- [ ] Test mit frontend
- [ ] Nginx einrichten
- [ ] test / staging / prod-Config anpassen

Aufrufe aus dem Frontend:

- `POST /api/shop` (Shop anlegen, setzt das Login-Cookie für die Shops)
- `POST /api/image/shop` (Bild hochladen, als Response kommt die Image-ID)
- `PUT /api/shop` (Shop bearbeiten, Image-ID mitschicken)

**Comment by phxql** [comment]
# Ideen für den Speicherort der Bilder

## Idee 1: In der Datenbank speichern

Wir speichern die Bilder als `bytea` in der Datenbank, schreiben einen RestController um die zu lesen, und generieren für das Frontend einen Link auf diesen Controller.

- PRO: Backup der Datenbank reicht, um auch die Bilder zu backuppen
- CON: Performance, da die Daten durch das Java-Backend müssen

## Idee 2: Bilder ins Filesystem schreiben

Wir schreiben die Bilder ins Dateisystem, richten eine subdomain in nginx ein (z.b. `images.lokaler.kaufen`) der als webroot den Ordner mit den Bildern hat und generieren für das Frontend einen Link auf den nginx.

- PRO: nginx tut das, was er am besten kann: Statische files ausliefern
- PRO: Können wir abartig cachen (Beim Update löschen wir das alte Bild und legen es neu unter anderem Namen ab)
- CON: Backup der Datenbank schließt die Bilder nicht ein, wir brauchen dann noch ein Backup der kompletten VM oder des Bilder-Ordners

## Idee 3: Speichern der Bilder im [GCP Cloud Storage](https://cloud.google.com/storage)

Wir laden die Bilder in ein Bucket zur GCP hoch, und generieren einen Read-only-Link auf das Bild, den wir ans backend geben können

- PRO: Einfaches Backup (einfach den Cloud Storage mit ins Backup nehmen)
- PRO: Daten fließen nicht über unsere VM, sondern Google kümmert sich darum
- CON: Wir müssen GCP Cloud Storage anbinden
- CON: Kosten (?)

**Comment by dashuber** [comment]
Wir sollten uns noch überlegen, was wir mit Shops machen, die kein Bild hochladen. Default Bild? Nicht anzeigen?

**Comment by dashuber** [comment]
Idee für einen Platzhalter: 
![grafik](https://user-images.githubusercontent.com/35682823/78462448-53d68980-76d2-11ea-99a7-aa9f3376c174.png)

**Comment by fuchshuber** [comment]
@phxql Meine Empfehlung: Die Daten nicht auseinanderziehen. Speichert die Bilder in der DB. Falls das irgendwann zu langsam ist, oder zu viel RAM benötigt (was bei den paar kBs lange kein Problem ist), kann man einen Cache reinklemmen (Java-App oder im NGNIX). Daten ins lokale Filesystem (als Primärdatenspeicher) zu schreiben, sollte man bei Cloud-Native Apps vermeiden.

**Comment by phxql** [comment]
In den Master gemerged und auf Test-Umgebung ausgerollt.
