### ISSUE TITLE
[FRONTEND] CSS Styling für "Als Ladenbesitzer registrieren" im Footer

### ISSUE THREAD

**Issue by dashuber** [qaware/wir-vs-virus#22]
Click auf "Als Ladenbesitzer registrieren" führt eine Methode aus und ist kein RouterLink. Das hat das CSS zerschossen. Muss einheitlich für alle Links im Footer gemacht werden.

**Comment by qa-schweikl** [comment]
Ich habe das Link-Styling nachgebaut.
