### ISSUE TITLE
API: Shop creation: ContactTypes und dazugehörige Information (Nummer, Email) speichern

### ISSUE THREAD

**Issue by phxql** [qaware/wir-vs-virus#29]

**Comment by phxql** [comment]
Contact Types werden gespeichert, nur die dazugehörige Telefonnummer, etc. noch nicht.

**Comment by vlow** [comment]
In MVP verschoben wegen #118 und #128 (siehe auch #126)

**Comment by phxql** [comment]
Ich kümmer mich drum.

**Comment by vlow** [comment]
@zalintyre hat da schon einiges gemacht gestern, stimmt euch am besten kurz ab.

**Comment by phxql** [comment]
Jep, @zalintyre macht das.
