### ISSUE TITLE
Frontend: Admin UI

### ISSUE THREAD

**Issue by Rhal95** [qaware/wir-vs-virus#32]
[Mockup](https://www.lucidchart.com/documents/edit/25d09900-a988-4a09-9811-544996aff860/thpIy6b59uIp)

**Comment by dashuber** [comment]
Können wir uns auf eine einheitliche Login Komponente einigen, egal ob Admin oder Ladenbesitzer Login? Ich find die von @defaude schon ziemlich gut: https://github.com/qaware/wir-vs-virus/blob/master/frontend/src/app/login-page/login-page.component.html
Müssten die Komponente dafür nur rausziehen.

**Comment by Rhal95** [comment]
Die Login Komponente sollte schon exakt die gleiche sein wie die für Ladenbesitzer. Also lediglich der Seitentitel und die url an die der Login Request gesendet werden sind unterschiedlich

**Comment by dominikhaas** [comment]
Ich schau mir die Übersichtsseite an. Feature branch: feature/32-admin-gui

**Comment by dashuber** [comment]
Ich bin an der DetailsPage dran

**Comment by dashuber** [comment]
Frontendseitig ist alles fertig, wir brauchen nur noch den `/api/admin/shop/{id}` Im Backend, sowie die Values der ContactTypes. Wie weit ist das @phxql @zalintyre?

**Comment by dashuber** [comment]
Passt soweit und ist gemerged, die ContactTypes fehlen nach wie vor backendseitig. Da müssen wir evtl. nochmal nacharbeiten, wenn's soweit ist.
