### ISSUE TITLE
Reservierung absagen Link

### ISSUE THREAD

**Issue by phxql** [qaware/wir-vs-virus#36]
* Link in Mail einbauen
  * Dafür JWT generieren, das die Reservation ID enthält
* Frontend-Guys bescheid sagen, dass die den Link unterstützen
* API bauen, um Reservation wieder zu löschen
  * Dabei JWT aus Request (gleiches wie im Link in der Mail) validieren und dann die Reservierung löschen
  * Emails an Shop und Kunde schicken

**Comment by phxql** [comment]
In der Mail ist ein Link in der Form `http://localhost:4200/#/cancel-reservation?token={{ token }}`. Frontend muss diesen Link unterstützen und den Call ans Backend absetzen.

API: tbd

**Comment by phxql** [comment]
Backend API um die Reservierung abzusagen:

```
DELETE {{ host }}/api/reservation?token={{ token }}
```

**Comment by phxql** [comment]
Backend done, Frontend kann loslegen!

**Comment by phxql** [comment]
@dashuber :)

**Comment by dashuber** [comment]
done
