### ISSUE TITLE
UI: Beim Klick auf den Header muss man die PLZ nochmal eingeben

### ISSUE THREAD

**Issue by phxql** [qaware/wir-vs-virus#39]
Seltsame UX, ich würde die PLZ cachen, solange der User die Seite offen hat. Beim Klick auf den Header dann auf die Liste der Shops.

**Comment by dashuber** [comment]
Momentan haben wir noch kein Caching o. Ä. eingebaut, alles läuft über Params in der URL. Muss man sich noch überlegen, wie man das umsetzt und wie aufwendig das dann ist
