### ISSUE TITLE
Filtern wir Ergebnisse, die über x Km sind?

### ISSUE THREAD

**Issue by phxql** [qaware/wir-vs-virus#4]
Z.b. ich suche in München, da gibts den laden aber nicht. Bekomme ich dann berlin?

**Comment by vlow** [comment]
Zum Start haben wir vsl. sehr wenig Einträge. Je mehr wir hier anzeigen können, umso besser hooken wir hier Kunden. Wenn es anfängt unübersichtlich zu werden, lösen wir dieses Luxusproblem mit solchen Filtern.
