### ISSUE TITLE
Slots auch für kommende Tage anzeigen?

### ISSUE THREAD

**Issue by phxql** [qaware/wir-vs-virus#41]

**Comment by vlow** [comment]
Benötigt zumindest eine fachliche Klärung darüber, wie mit solchen Terminen im Fall einer Deaktivierung oder von Urlaub umgegangen werden soll. Daher geblockt von #34.

**Comment by dominikhaas** [comment]
Macht total Sinn. Die Seite ist als Kunde im Feierabend unbenutzbar. 

￼

**Comment by dominikhaas** [comment]
<img width="859" alt="image" src="https://user-images.githubusercontent.com/3669640/77805009-37f33800-7081-11ea-8342-c11785b4384e.png">

**Comment by vlow** [comment]
Ja, weil die Läden halt zu haben. Wir brauchen ein sinnvolles UI Design für die Ansicht der nächsten Tage. Ideen?

**Comment by vlow** [comment]
Vorschlag: "Morgen" oder "Weitere Termine" Link anzeigen und dann die gleiche Seite für den nächsten Tag anzeigen. Andere Option: Dropdown mit den nächsten 7 Tagen anzeigen.

Generell dann sinnvoll: Link auf den nächsten Tag mit freien Öffnungszeiten in die Meldung einfügen, dass heute keine Slots mehr verfügbar sind, z.B. "Heute gibt es keine Termine mehr, aber schau mal am _Dienstag_..." mit Link auf den nächsten Öffnungstag.

Wichtig beim Design, es muss immer klar sein, an welchem Tag man sich befindet. Daher würde ich dabei bleiben, per default immer heute anzuzeigen und den User explizit einen anderen Tag auswählen zu lassen, wenn keine Slots mehr frei oder vorhanden sind. Das sollten wir ihm dann aber so leicht wie möglich machen.

**Comment by vlow** [comment]
Generell wäre es auch sinnvoll, den Text für "Heute keine Termine" auf "Heute keine Termine mehr" anzupassen. Ich vermute, das klingt auch in dem Fall richtiger, dass es heute gar keine Termine gab, und der technische Aufwand, da eine Fallunterscheidung einzubauen, erscheint mir als Overkill.

**Comment by dominikhaas** [comment]
Vielleicht könnte man einen Quickfix machen: Heute & morgen als zwei Bereiche anzeigen (oder heute und nächster Tag an dem geöffnet ist).
Dasnn bräuchte man keine Eingaben, etc. Der existierende Service sollte dann halt zwei Tage mit Slots liefern.

**Comment by phxql** [comment]
Ich bereite da mal Backend-seitig was vor.

**Comment by phxql** [comment]
Backend API angepasst. Slots liefern nun Slots für die nächsten 7 Tage, gruppiert bei Offset von today.

```json
{
    "slots": {
        "0": [
            {
                "id": "2020-03-29T16:40",
                "date": "2020-03-29",
                "start": "16:40",
                "end": "16:55",
                "available": true
            }
        ],
        "1": [
            {
                "id": "2020-03-30T08:00",
                "date": "2020-03-30",
                "start": "08:00",
                "end": "08:15",
                "available": true
            },
            {
                "id": "2020-03-30T08:20",
                "date": "2020-03-30",
                "start": "08:20",
                "end": "08:35",
                "available": true
            }
        ]
    }
}
```

**Comment by dashuber** [comment]
done im Frontend
