### ISSUE TITLE
Inhalte für "Datenschutz" und "Impressum" Seite anlegen

### ISSUE THREAD

**Issue by rohleder** [qaware/wir-vs-virus#44]
Inhalte für "Datenschutz" und "Impressum" Seite anlegen:
- https://demo.lokaler.kaufen/#/imprint
- https://demo.lokaler.kaufen/#/privacy

**Comment by vlow** [comment]
Hier sind vor allem noch rechtliche Anforderungen zu klären, daher blockt #69 diesen Issue. Der technische Change selber ist dann klein.

**Comment by vlow** [comment]
Datenschutz Seite angelegt.

**Comment by phxql** [comment]
In der Datenschutzerklärung fehlt noch, wieso wir die Kontaktdaten der Händler speichern.

**Comment by vlow** [comment]
done
