### ISSUE TITLE
Registierung Laden: Passwort Validierung benötigt Hinweis

### ISSUE THREAD

**Issue by rohleder** [qaware/wir-vs-virus#45]
Bei der Registierung eines Ladens sollte bei Passwörtern, die zu kurz sind (< 14 Zeichen) ein konkreter Hinweis kommen, ansonsten versteht man nicht, weshalb das Passwort nicht akzeptiert wird.

**Comment by vlow** [comment]
@dashuber das ist fertig, oder?

**Comment by dashuber** [comment]
Ja! Password Strength und Info Box ist da
