### ISSUE TITLE
Anlegen von Läden: "Back" und "Reset" Button umbenennen

### ISSUE THREAD

**Issue by rohleder** [qaware/wir-vs-virus#46]
Am Ende des Anlegens von Läden erscheinen zwei Buttons:

- "Back" in "Zurück" umbenennen
- "Reset" in "Zürücksetzen" umbenennen

**Comment by dashuber** [comment]
Reset Button hab ich entfernt, keiner will seinen kompletten Shop zurücksetzen. Und dann haben wir nicht "Zurück" und "Zurücksetzen" direkt nebeneinander.
