### ISSUE TITLE
Passwort vergessen Funktion für Laden Registrierung

### ISSUE THREAD

**Issue by rohleder** [qaware/wir-vs-virus#47]
Passwort vergessen Funktion für die Laden Registrierung

**Comment by dashuber** [comment]
@phxql ist diese Funktion im Backend schon drin?

**Comment by phxql** [comment]
Nein.

**Comment by phxql** [comment]
```
POST {{ host }}/api/shop/send-password-reset-link
Accept: application/json
Content-Type: application/json

{
    "email": "moe@localhost"
}
```

In der Mail ist dann ein Link aufs Frontend drin, z.B.

http://localhost:4200/#/reset-shop-password?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtb2VAbG9jYWxob3N0IiwiaXNzIjoibWVyY3VyeS1wYXNzd29yZC1yZXNldCJ9.11CYC7igayF1UesJ7KaBFvq2DLHmqjy367w1ggUjxo8

Mit diesem Token kann man dann das Backend aufrufen:

```
POST {{ host }}/api/shop/reset-password?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtb2VAbG9jYWxob3N0IiwiaXNzIjoibWVyY3VyeS1wYXNzd29yZC1yZXNldCJ9.11CYC7igayF1UesJ7KaBFvq2DLHmqjy367w1ggUjxo8
Accept: application/json
Content-Type: application/json

{
    "password": "new-password"
}
```

**Comment by phxql** [comment]
Backend-Seite ist fertig.

**Comment by dashuber** [comment]
done
