### ISSUE TITLE
UI: Shop Creation: Öffungs-Uhrzeiten sollten nur für die Tage angezeigt werden, die ich oben in den Bobbels aktiviert hab

### ISSUE THREAD

**Issue by phxql** [qaware/wir-vs-virus#48]

**Comment by vlow** [comment]
Idealerweise sollten die Eingabefelder für deaktivierte Tage klar sichtbar ausgegraut werden.

**Comment by dashuber** [comment]
Tag ausgegraut und Input field disabled

**Comment by dashuber** [comment]
done! Und es sieht richtig nice aus.
