### ISSUE TITLE
API: Requestvalidierung

### ISSUE THREAD

**Issue by phxql** [qaware/wir-vs-virus#55]
Bisher können fehlerhafte Requests noch zu 500er führen.

**Comment by phxql** [comment]
Habe schon relativ viel validierung eingebaut. An manchen stellen fehlt noch eine regex validierung und maximale länge.

**Comment by zalintyre** [comment]
@phxql Validation für IDs ist eingebaut.

Was meintest du mit diesen Kommentaren? Was sollen wir da validieren?

```
// TODO: Validate pattern
private String city;
```

**Comment by phxql** [comment]
Alphanumerische Zeichen, minimale & maximale Länge z.b.
