### ISSUE TITLE
DevOps: Backups der Datenbank

### ISSUE THREAD

**Issue by zalintyre** [qaware/wir-vs-virus#57]
Die PostgresSQL-Datenbank muss in regelmäßigen Abstand gesichert werden.

**Comment by vlow** [comment]
Gestern ausprobiert: Wir haben alle 24h Backups. Das Wiedereinspielen klappt gut. @zalintyre @phxql Reicht uns das?

**Comment by phxql** [comment]
Ja.

**Comment by phxql** [comment]
Fürs erste auf jeden Fall.
