### ISSUE TITLE
UI: Vorschläge beim Eingeben von PLZ/Ort anzeigen

### ISSUE THREAD

**Issue by FelixKelm** [qaware/wir-vs-virus#71]
Der Controller im Backend existiert schon und gibt passende Suggestions zurück. Er muss noch in die UI integriert werden.

Beispiel:
REST-Service: /api/location/suggestions?query=rosenh
Ergebnis:
{
  "locationSuggestions": [
    {
      "countryCode": "DE",
      "zipCode": "83022",
      "placeName": "Rosenheim",
      "adminName1": "Bayern",
      "adminName2": "Upper Bavaria",
      "adminName3": "Rosenheim"
    }, ...

**Comment by vlow** [comment]
@defaude @dashuber @Rhal95 @qa-schweikl  Dear frontend Duderiñas, PLZ kurz Schätzung validieren. Wär sehr cool, wenn es das Feature noch in den MVP schaffen würde. Aus dem Bauch raus würd ich den Aufwand dafür aber mindestens bei medium sehen.

**Comment by vlow** [comment]
Annahme: Wir schlagen Autocompletion für den Ort vor und ergänzen Input-Validierung.

**Comment by FelixKelm** [comment]
Ich schau mir gerade mal an ob ich das reinhacken kann. Danach sollte aber mal ein UI-Dude drüber schauen ;-)

**Comment by dashuber** [comment]
Da ich noch keine Ahnung hab, wie das funktioniert, hab ich mal medium geschätzt.

**Comment by FelixKelm** [comment]
Ist auf dem Branch #71
* Es sollte noch ein debounce rein, damit nicht bei jedem Keystroke ein REST-Call passiert.
* Wenn man einen Städtenamen eingibt und Return drückt, konvertiert er nicht zum zipcode, sondern schickt den Städtenamen zur Suche, das muss man noch ändern.

**Comment by vlow** [comment]
Felix hat das Feature eingebaut und um ein Review gebeten. @defaude @dashuber @qa-schweikl kann sich das einer von euch mal ansehen?

**Comment by dashuber** [comment]
Ich habe die Eingabe von Text verboten, man kann nur noch Ziffern und maximal 5 davon eingeben.

**Comment by vlow** [comment]
Wir könnten überlegen, Texteingaben zu erlauben. Dann könnte man auch nach Orten suchen. Generell ganz charmant, dann stimmen aber halt die Distanzen nicht mehr richtig.

**Comment by dashuber** [comment]
UI seitig funktioniert das ganze jetzt 🎉 
Allerdings bekomme ich vom Backend falsch sortierte Locations, die Vorschläge sollen sortiert nach dem vordesten Match werden. Beispiel: 818 soll auf 81827 oder 81825 completen, bevor es auf 18185 completed.

**Comment by phxql** [comment]
Ich fix den Backend-Part. Kann ich das dann in den Master mergen oder muss Frontend noch was tun? Würde ungern langlebige Feature Branches haben.

**Comment by dashuber** [comment]
Frontend müsste tun, gib einfach nen kurzen ping, wenn du soweit bist, dann teste ich

**Comment by FelixKelm** [comment]
Debouncing wäre noch sinnvoll, falls es noch nicht drin ist. Damit wir nicht massig Requests absetzen.

Mir ist gestern noch aufgefallen, dass man den eingegebenen Text mit Return oder Button-Klick abschicken kann. Wenn dann noch der Text und keine PLZ im Feld steht, findet man nix. Vll können wir die Suche unterbinden, bis eine PLZ drin steht.

**Comment by dashuber** [comment]
ist alles frontend seitig gefixt. debounce hab ich auf 100ms gestellt, können wir aber gern noch erhöhen

**Comment by phxql** [comment]
Mit Flo besprochen: wir bauen folgende Logik: Autocomplete nur auf PLZ.

Wenn man nach 818 sucht, kommen zuerst die, die mit 818 anfangen, danach die, die auch 818 irgednwo drin haben.

Relativ simpel: erst `LIKE 818%`, dann an diese Liste `LIKE %818%` anhängen. Inklusive Namen ans Frontend geben.

Bau ich heute abend ein.

**Comment by dashuber** [comment]
perfekt 👍

**Comment by phxql** [comment]
Done. Ich hab die API etwas angepasst, also bitte nochmal ins Swagger schauen:

```
╰─$ curlie ":8080/api/location/suggestion?zipCode=85579"                                                                                                                                                                                  7 ↵
HTTP/1.1 200 
Content-Type: application/json
Transfer-Encoding: chunked
Date: Tue, 24 Mar 2020 16:34:28 GMT

{
    "suggestions": [
        {
            "countryCode": "DE",
            "zipCode": "85579",
            "placeName": "Neubiberg"
        }
    ]
}
```

**Comment by dashuber** [comment]
done, hab jetzt auch noch eine Validierung eingebaut auf die Suggestions, sodass kein Call ans Backend geht, wenns die PLZ nicht gibt
