### ISSUE TITLE
DevOps: SonarQube aufsetzen und integrieren

### ISSUE THREAD

**Issue by vlow** [qaware/wir-vs-virus#72]
Bitte Sonar mit dem QAway in den Build integrieren.

**Comment by fuchshuber** [comment]
Werde es auf https://sonarcloud.io/ integrieren. Es gibt dort aber schon eine QAware-Org. Kann dort aber momentan kein Projekt dort anlegen. Habe bei @lreimer angefragt.

**Comment by lreimer** [comment]
@fuchshuber Bist jetzt Admin.
Projekt ist initial angelegt. Gradle Konfiguration und CI Integration stehen aus. Details per Slack.

**Comment by lreimer** [comment]
Coverage integrated. Unfortunately Sonarcloud does not support Groovy as a language, so coverage is there, but the test sources are not displayed.

**Comment by vlow** [comment]
Sonar läuft, Ticket erledigt.
