### ISSUE TITLE
URLs in ControllerServices falsch: Double Slashes

### ISSUE THREAD

**Issue by FelixKelm** [qaware/wir-vs-virus#79]
Beim Aufruf der Service-Methoden wird die Request-URL aus basepath und dem Service-Path falsch zusammengestzt, das zu doppelten Slashes und damit 404 führt.

Beispiel:
basePath = '//localhost:4200/';
...('get',`${this.basePath}/api/location/suggestions`, ...

Daraus entsteht http://localhost:4200**//**api/location/suggestions => 404

Die ControllerServices sehen generiert aus. Wie bekommen wir das gefixt?

**Comment by dashuber** [comment]
Wir nehmen die Controller nicht her ;-)

**Comment by dominikhaas** [comment]
Erstmal zurückgestellt, wegen Diskussion Pro Contra Codegen

**Comment by defaude** [comment]
Ich erstell morgen ein schönes follow-up Ticket :)
