### ISSUE TITLE
Frontend: Umgang mit leeren Beschreibungen

### ISSUE THREAD

**Issue by vlow** [qaware/wir-vs-virus#81]
Wenn Beschreibungen leer sind, zeigen wir ein leeres div an.

Quick-Win: Grauen Text mit "Ladenname hat noch keine Beschreibung hinterlegt." anzeigen.

Ordentliche Lösung: Läden müssen mindestens x Zeichen Beschreibung bei der Registrierung anlegen. Wenn wir das vor dem MVP schaffen, brauchen wir keine DB Migration.

**Comment by dashuber** [comment]
dank @dominikhaas können wir dieses issue schließen 👍
