### ISSUE TITLE
Volltextsuche mit leerer Eingabe erzeugt Fehler

### ISSUE THREAD

**Issue by rohleder** [qaware/wir-vs-virus#83]
Wenn ich nach einem Laden per Volltextsuche suche und dann den Suchtext wieder entferne um nach allen Läden zu suchen erhalte ich einen Fehler, siehe hier:

![image](https://user-images.githubusercontent.com/11029373/77406587-2d048300-6db5-11ea-814e-48269c473ec4.png)

**Comment by dashuber** [comment]
danke @dominikhaas fürs Fixen!
