### ISSUE TITLE
Textverbesserung Buchungs-Email an User

### ISSUE THREAD

**Issue by rohleder** [qaware/wir-vs-virus#84]
Eine Schönheitssache für die Email an einen User:
- nach "zwischen " sollte kein Zeilenumbruch sein
- bei den Uhrzeiten noch " Uhr" als Suffix ergänzen

![image](https://user-images.githubusercontent.com/11029373/77407007-c9c72080-6db5-11ea-99fa-2760878f14ef.png)

**Comment by vlow** [comment]
@phxql Allgemeine Frage: Sind unsere E-Mails Templates?

**Comment by phxql** [comment]
Ja, siehe https://github.com/qaware/wir-vs-virus/tree/master/backend/src/main/resources/email
