### ISSUE TITLE
Einheitliche Logos

### ISSUE THREAD

**Issue by vlow** [qaware/wir-vs-virus#86]
Wir haben die Logos von Doris bekommen. Todos: Korb an das a von kaufen umhängen und ggf. die Farbe des Henkels anpassen. Dann darauf basierend ein neues Favicon ziehen.

**Comment by FelixKelm** [comment]
Hab die svgs mal im qastorage abgelegt unter [\\qastorage\Mitarbeiter\Felix Kelm\lokaler-laufen-svgs](\\qastorage\Mitarbeiter\Felix Kelm\lokaler-laufen-svgs)

**Comment by vlow** [comment]
done
