### ISSUE TITLE
Backend: Endpunkt ob die Shop Details eines Ladenbesitzers abzurufen

### ISSUE THREAD

**Issue by dashuber** [qaware/wir-vs-virus#94]
Nach Login des Ladenbesitzers brauch ich die Shop Details, damit er diese verändern kann und ich ein update ans Backend schicken kann.

**Comment by phxql** [comment]
`GET /api/shop/me` wäre ne coole URL. Shop ID dann ausm Token lesen, das im Cookie steckt (AuthenticatonHelper verwenden).

**Comment by phxql** [comment]
Related: #95

**Comment by zalintyre** [comment]
Kommentar: Evtl. sollte man den `ShopController` aufteilen in die Ladenbesitzer- und die Kundensicht.

**Comment by zalintyre** [comment]
`GET /api/shop/me` gibt gleich ein `ShopOwnerDetailDto` zurück.
